const chargerData = [
    {
        percent: 65,
        status: 'Charging',
        remainingTime: '2h 15m',
        cap: 111.8,
        capMax: 200,
        chargerName: 'SOC No.1',
        evCar: 'EV1-001',
        chargeDate: '2025-01-04',
        chargingNum: "2",
        startTime: '04:00',
        endTime: '04:20',
        issue: '',
    },
    {
        percent: 25,
        status: 'Charging',
        remainingTime: '4h 30m',
        cap: 60.5,
        capMax: 200,
        chargerName: 'SOC No.2',
        chargingNum: "1",
        evCar: 'EV1-002',
        chargeDate: '2025-01-04',
        startTime: '04:10',
        endTime: '06:40',
        issue: '',
    },
    {
        percent: 80,
        status: 'Charging',
        remainingTime: '0m',
        cap: 200,
        capMax: 200,
        chargerName: 'SOC No.3',
        chargingNum: "2",
        evCar: 'EV1-003',
        chargeDate: '2025-01-04',
        startTime: '03:30',
        endTime: '04:30',
        issue: '',
    },
    {
        percent: 100,
        status: 'Finishing',
        remainingTime: '0m',
        cap: 0,
        capMax: 200,
        chargerName: 'SOC No.4',
        chargingNum: "2",
        evCar: 'EV1-004',
        chargeDate: '2025-01-04',
        startTime: '',
        endTime: '',
        issue: '',
    },
    {
        percent: 0,
        status: 'Available',
        remainingTime: '',
        cap: 0,
        capMax: 200,
        chargerName: 'SOC No.5',
        chargingNum: "0",
        evCar: '',
        chargeDate: '',
        startTime: '',
        endTime: '',
        issue: '',
    },
    {
        percent: 0,
        status: 'Unavailable',
        remainingTime: '',
        cap: 0,
        capMax: 200,
        chargerName: 'SOC No.6',
        chargingNum: "0",
        evCar: '',
        chargeDate: '',
        startTime: '',
        endTime: '',
        issue: '503 : Service Unavailable',
    },
];

export default chargerData;