const chargerData = [
    {
        id: 1,
        venderStationId: 418,
        stationName: '(JC) EV Station ท่าเรือ JC',
        railId: 1,
        serialNumber: 'BD04010Z009',
        chargerName: 'SCU 300kW No.10',
        truckNo: null,
        port1: {
            mac: null,
            status: 'Unvailable',
            power: null,
            soc: null,
            error: "Overheat",
            startTime: null,
            endTime: null,

        },
        port2: {
            mac: null,
            status: 'Unvailable',
            power: null,
            soc: null,
            error: "Overheat",
            startTime: null,
            endTime: null,

        },
        remainingTime: null,
    },
    {
        id: 2,
        venderStationId: 403,
        stationName: '(NKL) EV Station นครหลวง',
        railId: 1,
        serialNumber: 'BD04010Z001',
        chargerName: 'SCU 300kW No.5',
        truckNo: 'EV1-174',
        port1: {
            mac: '141FBA16640E',
            status: 'Charging',
            power: 130023.1,
            soc: 85.0,
            error: 'NoError',
            startTime: '2025-07-02T18:26:42.257',
            endTime: null,

        },
        port2: {
            mac: null,
            status: 'Charging',
            power: 101362.3,
            soc: 85.0,
            error: 'NoError',
            startTime: '2025-07-02T18:26:42.257',
            endTime: null,

        },
        remainingTime: '2h 30min',
    },
    {
        id: 3,
        venderStationId: 403,
        stationName: '(NKL) EV Station นครหลวง',
        railId: 1,
        serialNumber: 'BD04010Z006',
        chargerName: 'SCU 300kW No.6',
        truckNo: 'EV1-063',
        port1: {
            mac: '141FBA16640E',
            status: 'Available',
            power: null,
            soc: null,
            error: 'NoError',
            startTime: '2025-07-02T17:54:16.633',
            endTime: null,

        },
        port2: {
            mac: null,
            status: 'Available',
            power: 137707.2,
            soc: 72.0,
            error: 'NoError',
            startTime: '2025-07-02T17:54:16.633',
            endTime: null,

        },
        remainingTime: 'null',
    },
    {
        id: 4,
        venderStationId: 403,
        stationName: '(NKL) EV Station นครหลวง',
        railId: 1,
        serialNumber: 'BD04010Z002',
        chargerName: 'SCU 300kW No.7',
        truckNo: 'EV1-048',
        port1: {
            mac: '141FBA16643D',
            status: 'Charging',
            power: 0.0,
            soc: 96.0,
            error: 'NoError',
            startTime: '2025-07-03T03:46:54.8',
            endTime: null,

        },
        port2: {
            mac: null,
            status: 'Charging',
            power: 137208.5,
            soc: 75.0,
            error: 'NoError',
            startTime: '2025-07-03T03:46:54.8',
            endTime: null,

        },
        remainingTime: '2h 30min',
    },
    {
        id: 5,
        venderStationId: 418,
        stationName: '(JC) EV Station ท่าเรือ JC',
        railId: 1,
        serialNumber: 'BD04010Z003',
        chargerName: 'SCU 300kW No.8',
        truckNo: null,
        port1: {
            mac: null,
            status: 'Unvailable',
            power: null,
            soc: null,
            error: null,
            startTime: null,
            endTime: null,

        },
        port2: {
            mac: null,
            status: 'Unvailable',
            power: null,
            soc: null,
            error: null,
            startTime: null,
            endTime: null,

        },
        remainingTime: null,
    },
];

export default chargerData;
